### PR TITLE
Switch from wooga/eredis to Nordix/eredis.

### PR DESCRIPTION
**Pull request by NikolaBorisov**
It looks like this fork is the more maintained version.

### CODE REVIEW

**Review by balusu-murali — COMMENTED** [review]
i think we have good tests for this repo. so if the tests pass - then yeah, lgtm.

**Review by vipin211 — APPROVED** [review]
It might be worthwhile to find the diff and document it in commit as part of the change.

**Comment by NikolaBorisov** [comment]
It looks like Nordix/ecredis is the more supported fork of ecredis. I talked a bit with the maintainer. However this PR faild to build, It looks like some rebar2/rebar3 issue. I will revisit this PR a bit later.

**Comment by NikolaBorisov** [comment]
I worked with the Nordix devs to fix their fork to build with rebar2. This one should be ready to merge. 
@vipin211 https://github.com/Nordix/eredis/blob/master/CHANGELOG.md 
Also this: https://github.com/redis/redis-doc/pull/1586#issuecomment-861855504

**Review by balusu-murali — COMMENTED** [review]
> I worked with the Nordix devs to fix their fork to build with rebar2. This one should be ready to merge.

so the problem was non-ascii characters in the app file?
i think we should soon have a version here instead of the master branch for eredis.

**Review by balusu-murali — APPROVED** [review]

**Comment by NikolaBorisov** [comment]
> > I worked with the Nordix devs to fix their fork to build with rebar2. This one should be ready to merge.
> 
> so the problem was non-ascii characters in the app file?
> i think we should soon have a version here instead of the master branch for eredis.

I till change it to a version when they do a release. For now master is ok.

**Review by balusu-murali — APPROVED** [review]

**Comment by NikolaBorisov** [comment]
This will help us fix this issue: 
https://github.com/Nordix/eredis/commit/46b79817f45bb250c122d285f6dc4fc30a198b90#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

**Pull request merged**
